export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const apiURL = 'http://localhost:8080/api';

export const CHANGE_CELL_VALUE = 'CHANGE_CELL_VALUE';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const CHANGE_NUM_OF_COLUMNS = 'CHANGE_NUM_OF_COLUMNS';
export const CHANGE_NUM_OF_ROWS = 'CHANGE_NUM_OF_ROWS';

// movement detecion
export const ADD_IMG_URL = 'ADD_IMG_URL';
export const UPDATE_SENSORS = 'UPDATE_SENSORS';
export const DISARM = 'DISARM';
export const GET_ALL_MESSAGES = 'GET_ALL_MESSAGES';
export const CHAT_ADD_MESSAGE = 'CHAT_ADD_MESSAGE';
export const CHAT_MESSAGE_IS_TYPING = 'CHAT_MESSAGE_IS_TYPING';
export const CHAT_REMOVE_MESSAGE = 'CHAT_REMOVE_MESSAGE';
// login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_START = 'REGISTRATION_START';
export const ALERT_SHOW = 'ALERT_SHOW';
export const ALERT_HIDE = 'ALERT_HIDE';

// login end
export const CHAT_UPDATE_MESSAGE_BY_ID = 'CHAT_UPDATE_MESSAGE_BY_ID';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';

export const FETCH_WINDOW_DATA_SUCCESS = 'FETCH_WINDOW_DATA_SUCCESS';
export const FETCH_WINDOW_SENSORS_SUCCESS = 'FETCH_WINDOW_SENSORS_SUCCESS';
